-- MySQL Script generated by MySQL Workbench
-- Wed Mar 12 22:51:39 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema spm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spm` DEFAULT CHARACTER SET utf8 ;
USE `spm` ;

-- -----------------------------------------------------
-- Table `spm`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spm`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` TEXT(50) NOT NULL,
  `password` TEXT(100) NOT NULL,
  `email` TEXT(100) NULL DEFAULT NULL,
  `phone` TEXT(20) NULL DEFAULT NULL,
  `nickname` TEXT(50) NULL DEFAULT NULL,
  `avatar` TEXT(255) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COMMENT = '用户';


-- -----------------------------------------------------
-- Table `spm`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spm`.`address` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `recipient` TEXT(50) NOT NULL,
  `phone` TEXT(20) NOT NULL,
  `province` TEXT(50) NOT NULL,
  `city` TEXT(50) NOT NULL,
  `district` TEXT(50) NOT NULL,
  `address` TEXT(255) NOT NULL,
  `is_default` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  CONSTRAINT `address_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `spm`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户收货地址';


-- -----------------------------------------------------
-- Table `spm`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spm`.`product_category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` TEXT(50) NOT NULL,
  `parent_id` INT(11) NULL DEFAULT NULL,
  `level` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '商品分类';


-- -----------------------------------------------------
-- Table `spm`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spm`.`store` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT(16) NOT NULL COMMENT '店铺名称',
  `describe` TEXT NULL,
  `address` TEXT(255) NOT NULL COMMENT '店铺所在地',
  `picture_path` TEXT(255) NULL,
  `create_at` DATETIME NOT NULL,
  `status` INT NOT NULL DEFAULT 0 COMMENT '店铺状态：审核中，正常，已打烊',
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_store_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `spm`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '商店表';


-- -----------------------------------------------------
-- Table `spm`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spm`.`product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` TEXT(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `stock` INT(11) NOT NULL COMMENT '存量',
  `category_id` INT(11) NULL COMMENT '所属分类',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `pictures` TEXT(255) NOT NULL COMMENT '商品介绍图片的所在路径',
  `store_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `product_ibfk_1`
    FOREIGN KEY (`category_id`)
    REFERENCES `spm`.`product_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `spm`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '商品';


-- -----------------------------------------------------
-- Table `spm`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spm`.`cart` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `quantity` INT(11) NOT NULL COMMENT '商品数量',
  `spec` TEXT(255) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `cart_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `spm`.`user` (`id`),
  CONSTRAINT `cart_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `spm`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户购物车';


-- -----------------------------------------------------
-- Table `spm`.`product_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spm`.`product_comment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `content` TEXT NOT NULL,
  `rating` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `status` INT NOT NULL DEFAULT 0 COMMENT '评论状态，所有人可见，仅商家可见',
  PRIMARY KEY (`id`),
  CONSTRAINT `product_comment_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `spm`.`user` (`id`),
  CONSTRAINT `product_comment_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `spm`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '商品评价';


-- -----------------------------------------------------
-- Table `spm`.`comment_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spm`.`comment_like` (
  `comment_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`comment_id`, `user_id`),
  CONSTRAINT `comment_like_ibfk_1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `spm`.`product_comment` (`id`),
  CONSTRAINT `comment_like_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `spm`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户的评论联系（方便查询）';


-- -----------------------------------------------------
-- Table `spm`.`coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spm`.`coupon` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` TEXT(100) NOT NULL COMMENT '优惠券名称',
  `effect` JSON NOT NULL COMMENT '优惠券使用效果，如最便宜商品降价20，总体九五折等。',
  `rules` JSON NOT NULL COMMENT '优惠券使用规则',
  `start_time` DATETIME NOT NULL COMMENT '启用时间',
  `end_time` DATETIME NOT NULL COMMENT '到期时间',
  `status` INT NOT NULL COMMENT '优惠券状态，未使用，已使用，已过期',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '优惠券';


-- -----------------------------------------------------
-- Table `spm`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spm`.`order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `address_id` INT(11) NOT NULL,
  `total_amount` DECIMAL(10,2) NOT NULL COMMENT '总金额',
  `payment_method` TEXT(50) NOT NULL COMMENT '支付方式',
  `status` INT NOT NULL COMMENT '状态，待发起，待支付，等待发货，运输中，已完成等',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `order_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `spm`.`user` (`id`),
  CONSTRAINT `order_ibfk_2`
    FOREIGN KEY (`address_id`)
    REFERENCES `spm`.`address` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '订单';


-- -----------------------------------------------------
-- Table `spm`.`order_logistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spm`.`order_logistics` (
  `product_id` INT(11) NOT NULL,
  `order_id` INT(11) NOT NULL,
  `tracking_number` TEXT(100) NOT NULL COMMENT '运单号',
  `status` TEXT(50) NOT NULL COMMENT '运单状态',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`product_id`, `order_id`),
  CONSTRAINT `logistics_ibfk_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `spm`.`order` (`id`),
  CONSTRAINT `fk_order_logistics_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `spm`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '订单中各个商品的物流';


-- -----------------------------------------------------
-- Table `spm`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spm`.`notification` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '唯一标识',
  `title` TEXT(100) NOT NULL COMMENT '消息标题',
  `content` TEXT NOT NULL COMMENT '内容',
  `created_at` DATETIME NOT NULL COMMENT '创建时间',
  `status` INT NOT NULL COMMENT '状态，已读，未读',
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  CONSTRAINT `fk_notification_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `spm`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '消息队列';


-- -----------------------------------------------------
-- Table `spm`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spm`.`order_item` (
  `order_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `quantity` INT(11) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `spec` TEXT(255) NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  CONSTRAINT `order_item_ibfk_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `spm`.`order` (`id`),
  CONSTRAINT `order_item_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `spm`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '订单和商品的连接';


-- -----------------------------------------------------
-- Table `spm`.`user_favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spm`.`user_favorites` (
  `user_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`, `product_id`),
  CONSTRAINT `product_favorite_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `spm`.`user` (`id`),
  CONSTRAINT `product_favorite_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `spm`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户收藏的商品（关联表）';


-- -----------------------------------------------------
-- Table `spm`.`upload_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spm`.`upload_record` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `file_path` TEXT(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  CONSTRAINT `upload_record_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `spm`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '上传记录';


-- -----------------------------------------------------
-- Table `spm`.`user_coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spm`.`user_coupon` (
  `user_id` INT(11) NOT NULL,
  `coupon_id` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`, `coupon_id`),
  CONSTRAINT `user_coupon_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `spm`.`user` (`id`),
  CONSTRAINT `user_coupon_ibfk_2`
    FOREIGN KEY (`coupon_id`)
    REFERENCES `spm`.`coupon` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户和优惠券的关联表';


-- -----------------------------------------------------
-- Table `spm`.`user_feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spm`.`user_feedback` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '反馈id',
  `user_id` INT(11) NOT NULL COMMENT '用户id',
  `content` TEXT CHARACTER SET 'utf8' NOT NULL COMMENT '反馈内容',
  `contact` TEXT(100) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '联系方式',
  `created_at` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  CONSTRAINT `user_feedback_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `spm`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户反馈表';


-- -----------------------------------------------------
-- Table `spm`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spm`.`admin` (
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_admin_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `spm`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '是否为管理员';


-- -----------------------------------------------------
-- Table `spm`.`verification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spm`.`verification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` INT NOT NULL DEFAULT -1 COMMENT '验证类型：管理员提权，店铺信息修改，商品信息修改，退货，注销账户等',
  `user_id` INT NOT NULL COMMENT '发起人',
  `reviewer_id` INT NOT NULL COMMENT '处理人',
  `status` INT NOT NULL DEFAULT 0 COMMENT '处理情况，未处理，已同意，已拒绝',
  `create_at` DATETIME NOT NULL COMMENT '发起时间',
  `update_at` DATETIME NOT NULL COMMENT '处理时间',
  `content` TEXT NOT NULL COMMENT '发起人输入内容',
  `reply` TEXT NOT NULL COMMENT '处理人处理意见',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `spm`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviewer_id`
    FOREIGN KEY (`reviewer_id`)
    REFERENCES `spm`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '验证表单';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
